cp /opt/config/upgrade_config/gvmesh.out /opt/greenvity/bkup/
cp /opt/config/upgrade_config/gvmesh_cli.out /opt/greenvity/bkup/
cp /opt/config/upgrade_config/llp_cli.out /opt/greenvity/bkup/
cp /opt/config/upgrade_config/llp_daemon.out /opt/greenvity/bkup/
cp /opt/config/upgrade_config/llp_http.out /opt/greenvity/bkup/
cp /opt/config/upgrade_config/mqtt_withSSL.out /opt/greenvity/bkup/mqtt/
cp /opt/config/upgrade_config/tcp_server.out /opt/greenvity/bkup/tcp/
mv /opt/config/upgrade_config/gvmesh.out /opt/greenvity/llp/
mv /opt/config/upgrade_config/gvmesh_cli.out /opt/greenvity/llp/
mv /opt/config/upgrade_config/llp_cli.out /opt/greenvity/llp/
mv /opt/config/upgrade_config/llp_daemon.out /opt/greenvity/llp/
mv /opt/config/upgrade_config/llp_http.out /opt/greenvity/llp/
mv /opt/config/upgrade_config/mqtt_withSSL.out /opt/greenvity/mqtt/
mv /opt/config/upgrade_config/ca.crt /opt/greenvity/mqtt/
mv /opt/config/upgrade_config/hostURL.txt /opt/greenvity/mqtt/
mv /opt/config/upgrade_config/topics.txt /opt/greenvity/mqtt/
mv /opt/config/upgrade_config/tcp_server.out /opt/greenvity/tcp/
mv /opt/config/upgrade_config/zigbeeApp /opt/greenvity/llp/net/zigbee/
mv /opt/config/upgrade_config/zll /opt/greenvity/llp/net/zigbee/
mv /opt/config/upgrade_config/ghdd.ko /opt/greenvity/ghdd/
cp /opt/config/upgrade_config/version.txt /opt/greenvity/llp/
cp /opt/config/upgrade_config/clearflash.sh /opt/greenvity/llp/
cp /opt/config/upgrade_config/llp_Dev_Config.sh /opt/greenvity/llp/
cp /opt/config/upgrade_config/track_host.sh /opt/greenvity/bkup/
cp /opt/config/upgrade_config/track_host.sh /opt/greenvity/llp/
cp /opt/config/upgrade_config/run_eth.sh /opt/greenvity/llp/
cp /opt/config/upgrade_config/run_wifi.sh /opt/greenvity/llp/