rm -f /opt/config/upgrade_config/$1
rm -f /opt/config/upgrade_config/gvmesh.out
rm -f /opt/config/upgrade_config/gvmesh_cli.out
rm -f /opt/config/upgrade_config/llp_cli.out
rm -f /opt/config/upgrade_config/llp_daemon.out
rm -f /opt/config/upgrade_config/llp_http.out
rm -f /opt/config/upgrade_config/mqtt_withSSL.out
rm -f /opt/config/upgrade_config/ca.crt
rm -f /opt/config/upgrade_config/hostURL.txt
rm -f /opt/config/upgrade_config/topics.txt
rm -f /opt/config/upgrade_config/tcp_server.out
rm -f /opt/config/upgrade_config/zigbeeApp
rm -f /opt/config/upgrade_config/zll
rm -f /opt/config/upgrade_config/ghdd.ko
rm -f /opt/config/upgrade_config/upgrade_config.txt
rm -f /opt/config/upgrade_config/version.txt
rm -f /opt/config/upgrade_config/clearflash.sh
rm -f /opt/config/upgrade_config/llp_Dev_Config.sh
rm -f /opt/config/upgrade_config/track_host.sh
rm -f /opt/config/upgrade_config/run_eth.sh
rm -f /opt/config/upgrade_config/run_wifi.sh